# Generated by Django 4.2 on 2025-03-15 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10)),
                ('is_child', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('berth_number', models.IntegerField(blank=True, null=True)),
                ('berth_type', models.CharField(blank=True, choices=[('LB', 'Lower Berth'), ('MB', 'Middle Berth'),
                                                                     ('UB', 'Upper Berth'), ('SU', 'Side Upper Berth'),
                                                                     ('SL', 'Side Lower Berth')], max_length=2,
                                                null=True)),
                ('status', models.CharField(
                    choices=[('CNF', 'Confirmed'), ('RAC', 'Reservation Against Cancellation'), ('WL', 'Waiting List')],
                    max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('passenger',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.passenger')),
            ],
        ),
    ]
