# Generated by Django 4.2 on 2025-03-17 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger',
            name='is_child',
        ),
        migrations.AddField(
            model_name='passenger',
            name='has_child',
            field=models.BooleanField(default=False),
        ),
    ]
