# Generated by Django 4.2 on 2025-03-18 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_remove_passenger_is_child_passenger_has_child'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
