# Generated by Django 4.2 on 2025-03-18 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_ticket_cancelled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='age',
            field=models.PositiveIntegerField(),
        ),
    ]
